# Generated by Django 6.0.7 on 2026-09-22 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Impressora / Setor')),
                ('observations', models.CharField(blank=True, max_length=255, verbose_name='Observação')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('minimum_quantity', models.PositiveIntegerField(default=1, help_text='Quando a quantidade chegar a este valor o toner é sinalizado para compra.', verbose_name='Quantidade Mínima')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Toner',
                'verbose_name_plural': 'Toners',
                'ordering': ['location', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TonerMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('toner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='app.toner', verbose_name='Toner')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Movimentação de Toner',
                'verbose_name_plural': 'Movimentações de Toner',
                'ordering': ['-created_at'],
            },
        ),
    ]
