# Generated by Django 6.0.7 on 2026-09-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_toner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toner',
            name='name',
            field=models.CharField(error_messages={'unique': 'Já existe um toner cadastrado com este nome.'}, max_length=100, unique=True, verbose_name='Modelo'),
        ),
    ]
